# Add Integers

the objective of this FFN model is too add two integers together and predict the right result. the integers are between, and including,  -10 and 10,

### Steps
1. data generation
2. determine independent and dependent features
3. split train and test data
4. convert to tensors
5. design model
6. train model
7. evaluate and experiment on model

In [60]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## 1. Data Generation

In [61]:
X = np.array([[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10],
                  [3,4,5,7,-5,5,-1,-5,-8,-4,-3,9,7,5,4,2,1,-9,-8,-7,-10]], dtype=np.float32)
X = X.reshape(21,2)
X.shape, X

((21, 2),
 array([[-10.,  -9.],
        [ -8.,  -7.],
        [ -6.,  -5.],
        [ -4.,  -3.],
        [ -2.,  -1.],
        [  0.,   1.],
        [  2.,   3.],
        [  4.,   5.],
        [  6.,   7.],
        [  8.,   9.],
        [ 10.,   3.],
        [  4.,   5.],
        [  7.,  -5.],
        [  5.,  -1.],
        [ -5.,  -8.],
        [ -4.,  -3.],
        [  9.,   7.],
        [  5.,   4.],
        [  2.,   1.],
        [ -9.,  -8.],
        [ -7., -10.]], dtype=float32))

In [62]:
y = []
for sub_array in X:
    print(sum(sub_array))
    y.append(sum(sub_array).item())

print(f'this is the updated temp list{y}')

y = np.array(y, dtype=np.float32)
y = y.reshape(21,1)
X.shape, y.shape

-19.0
-15.0
-11.0
-7.0
-3.0
1.0
5.0
9.0
13.0
17.0
13.0
9.0
2.0
4.0
-13.0
-7.0
16.0
9.0
3.0
-17.0
-17.0
this is the updated temp list[-19.0, -15.0, -11.0, -7.0, -3.0, 1.0, 5.0, 9.0, 13.0, 17.0, 13.0, 9.0, 2.0, 4.0, -13.0, -7.0, 16.0, 9.0, 3.0, -17.0, -17.0]


((21, 2), (21, 1))

## 3. Split train and test data

In [63]:
y.dtype, X.dtype, X, y

(dtype('float32'),
 dtype('float32'),
 array([[-10.,  -9.],
        [ -8.,  -7.],
        [ -6.,  -5.],
        [ -4.,  -3.],
        [ -2.,  -1.],
        [  0.,   1.],
        [  2.,   3.],
        [  4.,   5.],
        [  6.,   7.],
        [  8.,   9.],
        [ 10.,   3.],
        [  4.,   5.],
        [  7.,  -5.],
        [  5.,  -1.],
        [ -5.,  -8.],
        [ -4.,  -3.],
        [  9.,   7.],
        [  5.,   4.],
        [  2.,   1.],
        [ -9.,  -8.],
        [ -7., -10.]], dtype=float32),
 array([[-19.],
        [-15.],
        [-11.],
        [ -7.],
        [ -3.],
        [  1.],
        [  5.],
        [  9.],
        [ 13.],
        [ 17.],
        [ 13.],
        [  9.],
        [  2.],
        [  4.],
        [-13.],
        [ -7.],
        [ 16.],
        [  9.],
        [  3.],
        [-17.],
        [-17.]], dtype=float32))

In [76]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=1234)
X_train, y_train,  X_test, y_test

(array([[  0.,   1.],
        [ -2.,  -1.],
        [-10.,  -9.],
        [  6.,   7.],
        [  2.,   1.],
        [  5.,   4.],
        [  4.,   5.],
        [ 10.,   3.],
        [  8.,   9.],
        [  4.,   5.],
        [ -8.,  -7.],
        [ -7., -10.],
        [  7.,  -5.],
        [  2.,   3.],
        [ -9.,  -8.],
        [ -4.,  -3.]], dtype=float32),
 array([[  1.],
        [ -3.],
        [-19.],
        [ 13.],
        [  3.],
        [  9.],
        [  9.],
        [ 13.],
        [ 17.],
        [  9.],
        [-15.],
        [-17.],
        [  2.],
        [  5.],
        [-17.],
        [ -7.]], dtype=float32),
 array([[-4., -3.],
        [ 5., -1.],
        [-6., -5.],
        [ 9.,  7.],
        [-5., -8.]], dtype=float32),
 array([[ -7.],
        [  4.],
        [-11.],
        [ 16.],
        [-13.]], dtype=float32))

## 4. Convert to Tensors for training

In [77]:
# scale the data
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
# convert back to tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

X_train, X_test, y_train, y_test

(tensor([[  0.,   1.],
         [ -2.,  -1.],
         [-10.,  -9.],
         [  6.,   7.],
         [  2.,   1.],
         [  5.,   4.],
         [  4.,   5.],
         [ 10.,   3.],
         [  8.,   9.],
         [  4.,   5.],
         [ -8.,  -7.],
         [ -7., -10.],
         [  7.,  -5.],
         [  2.,   3.],
         [ -9.,  -8.],
         [ -4.,  -3.]]),
 tensor([[-4., -3.],
         [ 5., -1.],
         [-6., -5.],
         [ 9.,  7.],
         [-5., -8.]]),
 tensor([[  1.],
         [ -3.],
         [-19.],
         [ 13.],
         [  3.],
         [  9.],
         [  9.],
         [ 13.],
         [ 17.],
         [  9.],
         [-15.],
         [-17.],
         [  2.],
         [  5.],
         [-17.],
         [ -7.]]),
 tensor([[ -7.],
         [  4.],
         [-11.],
         [ 16.],
         [-13.]]))

In [ ]:
class FFNAddTwoIntegers(nn.Module):
    def __init__(self, input_size):
        super(FFNAddTwoIntegers, self).__init__()
        