# Add Integers

the objective of this FFN model is too add two integers together and predict the right result. the integers are between, and including,  -10 and 10,

### Steps
1. data generation
2. determine independent and dependent features
3. split train and test data
4. convert to tensors
5. design model
6. train model
7. evaluate and experiment on model

In [1]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler


A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.3.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/markalford/Desktop/FeedForwardLibrary/FeedFowardLibray/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/Users/markalford/Desktop/FeedForwardLibrary/FeedFowardLibray/lib/python3.11/site-packages/traitlets/config/application.py", line 1075, in launch_instance
    app.start()
  File "/Users/markalford/Desktop/FeedForwardLibrary/FeedFowardLibray/

## 1. Data Generation

In [2]:
X = np.array([[-10,-9,-8,-7,-6,-5,-4,-3,-2,-1,0,1,2,3,4,5,6,7,8,9,10],
                  [3,4,5,7,-5,5,-1,-5,-8,-4,-3,9,7,5,4,2,1,-9,-8,-7,-10]], dtype=np.float32)
X = X.reshape(21,2)
X.shape, X

((21, 2),
 array([[-10.,  -9.],
        [ -8.,  -7.],
        [ -6.,  -5.],
        [ -4.,  -3.],
        [ -2.,  -1.],
        [  0.,   1.],
        [  2.,   3.],
        [  4.,   5.],
        [  6.,   7.],
        [  8.,   9.],
        [ 10.,   3.],
        [  4.,   5.],
        [  7.,  -5.],
        [  5.,  -1.],
        [ -5.,  -8.],
        [ -4.,  -3.],
        [  9.,   7.],
        [  5.,   4.],
        [  2.,   1.],
        [ -9.,  -8.],
        [ -7., -10.]], dtype=float32))

In [3]:
y = []
for sub_array in X:
    print(sum(sub_array))
    y.append(sum(sub_array).item())

print(f'this is the updated temp list{y}')

y = np.array(y, dtype=np.float32)
y = y.reshape(21,1)
X.shape, y.shape

-19.0
-15.0
-11.0
-7.0
-3.0
1.0
5.0
9.0
13.0
17.0
13.0
9.0
2.0
4.0
-13.0
-7.0
16.0
9.0
3.0
-17.0
-17.0
this is the updated temp list[-19.0, -15.0, -11.0, -7.0, -3.0, 1.0, 5.0, 9.0, 13.0, 17.0, 13.0, 9.0, 2.0, 4.0, -13.0, -7.0, 16.0, 9.0, 3.0, -17.0, -17.0]


((21, 2), (21, 1))

## 3. Split train and test data

In [4]:
y.dtype, X.dtype, X, y

(dtype('float32'),
 dtype('float32'),
 array([[-10.,  -9.],
        [ -8.,  -7.],
        [ -6.,  -5.],
        [ -4.,  -3.],
        [ -2.,  -1.],
        [  0.,   1.],
        [  2.,   3.],
        [  4.,   5.],
        [  6.,   7.],
        [  8.,   9.],
        [ 10.,   3.],
        [  4.,   5.],
        [  7.,  -5.],
        [  5.,  -1.],
        [ -5.,  -8.],
        [ -4.,  -3.],
        [  9.,   7.],
        [  5.,   4.],
        [  2.,   1.],
        [ -9.,  -8.],
        [ -7., -10.]], dtype=float32),
 array([[-19.],
        [-15.],
        [-11.],
        [ -7.],
        [ -3.],
        [  1.],
        [  5.],
        [  9.],
        [ 13.],
        [ 17.],
        [ 13.],
        [  9.],
        [  2.],
        [  4.],
        [-13.],
        [ -7.],
        [ 16.],
        [  9.],
        [  3.],
        [-17.],
        [-17.]], dtype=float32))

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.20, random_state=1234)
X_train, y_train,  X_test, y_test

(array([[  0.,   1.],
        [ -2.,  -1.],
        [-10.,  -9.],
        [  6.,   7.],
        [  2.,   1.],
        [  5.,   4.],
        [  4.,   5.],
        [ 10.,   3.],
        [  8.,   9.],
        [  4.,   5.],
        [ -8.,  -7.],
        [ -7., -10.],
        [  7.,  -5.],
        [  2.,   3.],
        [ -9.,  -8.],
        [ -4.,  -3.]], dtype=float32),
 array([[  1.],
        [ -3.],
        [-19.],
        [ 13.],
        [  3.],
        [  9.],
        [  9.],
        [ 13.],
        [ 17.],
        [  9.],
        [-15.],
        [-17.],
        [  2.],
        [  5.],
        [-17.],
        [ -7.]], dtype=float32),
 array([[-4., -3.],
        [ 5., -1.],
        [-6., -5.],
        [ 9.,  7.],
        [-5., -8.]], dtype=float32),
 array([[ -7.],
        [  4.],
        [-11.],
        [ 16.],
        [-13.]], dtype=float32))

## 4. Convert to Tensors for training

In [6]:
# scale the data
#sc = StandardScaler()
#X_train = sc.fit_transform(X_train)
#X_test = sc.transform(X_test)
# convert back to tensors
X_train = torch.tensor(X_train, dtype=torch.float32)
X_test = torch.tensor(X_test, dtype=torch.float32)
y_train = torch.tensor(y_train, dtype=torch.float32)
y_test = torch.tensor(y_test, dtype=torch.float32)

X_train, X_test, y_train, y_test

(tensor([[  0.,   1.],
         [ -2.,  -1.],
         [-10.,  -9.],
         [  6.,   7.],
         [  2.,   1.],
         [  5.,   4.],
         [  4.,   5.],
         [ 10.,   3.],
         [  8.,   9.],
         [  4.,   5.],
         [ -8.,  -7.],
         [ -7., -10.],
         [  7.,  -5.],
         [  2.,   3.],
         [ -9.,  -8.],
         [ -4.,  -3.]]),
 tensor([[-4., -3.],
         [ 5., -1.],
         [-6., -5.],
         [ 9.,  7.],
         [-5., -8.]]),
 tensor([[  1.],
         [ -3.],
         [-19.],
         [ 13.],
         [  3.],
         [  9.],
         [  9.],
         [ 13.],
         [ 17.],
         [  9.],
         [-15.],
         [-17.],
         [  2.],
         [  5.],
         [-17.],
         [ -7.]]),
 tensor([[ -7.],
         [  4.],
         [-11.],
         [ 16.],
         [-13.]]))

In [8]:
from torch.utils.data import TensorDataset, DataLoader

# create tensorDatasets from the test and train data (both X and y)
train_dataset = TensorDataset(X_train, y_train)
test_dataset = TensorDataset(X_test, y_test)

# create tthe dataloaders from these datasets
train_loader = DataLoader(train_dataset, batch_size=4, shuffle=True)
test_loader = DataLoader(test_dataset, batch_size=4)

In [11]:
class FFNAddTwoIntegers(nn.Module):
    def __init__(self):
        super(FFNAddTwoIntegers, self).__init__()
        self.model = nn.Sequential(
            nn.Linear(2,16),
            nn.ReLU(),
            nn.Linear(16,8),
            nn.ReLU(),
            nn.Linear(8,1)
        )
    
    def forward(self, x):
        return self.model(x)
        

In [27]:
# train the model
model = FFNAddTwoIntegers()
criterion = nn.MSELoss()
optimizer = torch.optim.Adam(model.parameters(), lr = 0.01)

num_epochs = 300

for epoch in range(num_epochs):
    model.train()
    epoch_loss = 0.0

    for batch_X, batch_y in train_loader:
       
        y_pred = model(batch_X)
        loss = criterion(y_pred, batch_y)
        loss.backward()
        optimizer.step()
        optimizer.zero_grad()
        epoch_loss += loss.item()

    
    if (epoch + 1) % 10 == 0:
        print(f"Epoch {epoch+1}/{num_epochs}, Loss: {epoch_loss:.4f}")

Epoch 10/300, Loss: 19.2859
Epoch 20/300, Loss: 0.2664
Epoch 30/300, Loss: 0.1028
Epoch 40/300, Loss: 0.0661
Epoch 50/300, Loss: 0.0459
Epoch 60/300, Loss: 0.0309
Epoch 70/300, Loss: 0.0240
Epoch 80/300, Loss: 0.0179
Epoch 90/300, Loss: 0.0143
Epoch 100/300, Loss: 0.0111
Epoch 110/300, Loss: 0.0092
Epoch 120/300, Loss: 0.0079
Epoch 130/300, Loss: 0.0069
Epoch 140/300, Loss: 0.0071
Epoch 150/300, Loss: 0.0345
Epoch 160/300, Loss: 0.0293
Epoch 170/300, Loss: 0.0065
Epoch 180/300, Loss: 0.0066
Epoch 190/300, Loss: 0.0036
Epoch 200/300, Loss: 0.0038
Epoch 210/300, Loss: 0.0043
Epoch 220/300, Loss: 0.0026
Epoch 230/300, Loss: 0.0062
Epoch 240/300, Loss: 0.0242
Epoch 250/300, Loss: 0.0258
Epoch 260/300, Loss: 0.0036
Epoch 270/300, Loss: 0.0056
Epoch 280/300, Loss: 0.0018
Epoch 290/300, Loss: 0.0026
Epoch 300/300, Loss: 0.0017


In [32]:
example_1 = torch.tensor([[-10.,4.]])

# Set the model to evaluation mode
model.eval()

# Disable gradient calculation for inference
with torch.no_grad():
    prediction = model(example_1)

print("Predicted value:", prediction.item())

Predicted value: -7.5307745933532715


In [ ]:
example_1 = torch.tensor([[-10.,10.]])

# Set the model to evaluation mode
model.eval()

# Disable gradient calculation for inference
with torch.no_grad():
    prediction = model(example_1)

print("Predicted value:", prediction.item())

Predicted value: -3.4432244300842285


In [41]:
X_test

tensor([[-4., -3.],
        [ 5., -1.],
        [-6., -5.],
        [ 9.,  7.],
        [-5., -8.]])

In [ ]:

with torch.no_grad():
    for test_samples in X_test:
        prediction = model(test_samples)
        print("Predicted value:", prediction.item())



Predicted value: -6.999775409698486
Predicted value: 4.106655120849609
Predicted value: -10.999343872070312
Predicted value: 16.026309967041016
Predicted value: -13.055866241455078
